#!/usr/bin/env python
"""Push and watch a Kaggle run from here, without opening the website.

    python launch.py explain            # what each run proves, pushes nothing
    python launch.py shakedown          # TPU,  ~0.5h, proves the path
    python launch.py shakedown-gpu      # 2xT4, ~0.5h, proves the path
    python launch.py train              # large, ~8.5h, ends with a .gguf
    python launch.py status             # is it still going
    python launch.py fetch              # download the finished output

This exists because the thing that used to block it is fixed. llm67m's driver
says the kernel API has no field for choosing an accelerator, which was true:
a pushed kernel got one GPU and DDP never engaged, so the dual-T4 run had to be
started from the web editor. The CLI now takes `--accelerator`, and `TpuV5E8` is
in its accepted list, so the whole session can be started from a terminal.

What still cannot be automated from here: creating the account, phone
verification (the accelerator dropdown stays greyed out until you do it), and
generating the API token. Those are three minutes of clicking, once, and
`python launch.py status` tells you exactly which one is missing.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

REPO = "https://github.com/evanwang810/llm-reverse"

# Accelerator ids the CLI accepts, most preferred first. v5e-8 is what Kaggle
# ships today; v6e-8 is the newer one and worth falling back to rather than
# failing, since Kaggle rotates these without warning.
TPU_IDS = ("TpuV5E8", "TpuV6E8", "Tpu1VmV38")
GPU_IDS = ("NvidiaTeslaT4", "NvidiaTeslaP100")

# A shakedown is not a small training run. It is a list of things that can be
# broken, executed in order, and 2e7 tokens is enough to reach every one of them.
# Going bigger only buys you a better loss curve on a model you are going to
# throw away.
PROVES = [
    "the accelerator is real and the account is verified (a greyed-out "
    "dropdown silently falls back to CPU, which trains fine and slowly)",
    "the corpus streams from HuggingFace and the shard writer works",
    "the reversal is actually applied, visible as a loss spike then recovery",
    "the base model downloads and moves onto the device",
    "training steps run without recompiling every step (the classic XLA hang)",
    "a checkpoint gets written and pruned",
    "the export stage turns a checkpoint into a downloadable folder",
]

RUNS = {
    "shakedown": {
        "base": "small-tpu", "hours": "0.5", "tokens": "2e7", "device": "tpu",
        "env": {"EXPORT": "1"},
        "why": "half an hour to prove the TPU path end to end",
        "extra": "torch_xla imports, bf16 autocast works, and eight replicas "
                 "agree. tpu_preflight.py gates this in about two minutes, "
                 "which matters because TPU failures usually present as a hang "
                 "rather than an error.",
    },
    "shakedown-gpu": {
        "base": "small", "hours": "0.5", "tokens": "2e7", "device": "gpu",
        "env": {"EXPORT": "1"},
        "why": "half an hour to prove the dual-T4 path end to end",
        "extra": "DDP engages across both cards, and the fp16 GradScaler "
                 "settles instead of collapsing. Turing has no bf16, so this "
                 "is the run that tells you whether the loss scale is stable "
                 "on your base before you spend a long session on it.",
    },
    "train": {
        "base": "large", "hours": "8.5", "tokens": "1e9", "device": "tpu",
        "env": {"GGUF": "1",
                "TRAIN_EXTRA": "--keep-checkpoints 1 --keep-weights 2 "
                               "--milestone-every-min 0"},
        "why": "the real run, ending in a .gguf you can download",
        "extra": "Those TRAIN_EXTRA flags are the disk budget, not a "
                 "preference: /kaggle/working caps at 20 GB and one full "
                 "checkpoint of Qwen3-0.6B is 7.2 GB on its own. Run a "
                 "shakedown first; this one is eight and a half hours and TPU "
                 "failures do not announce themselves.",
    },
    "train-gpu": {
        "base": "large-gpu", "hours": "11.3", "tokens": "1e9", "device": "gpu",
        "env": {"GGUF": "1",
                "TRAIN_EXTRA": "--keep-checkpoints 1 --keep-weights 2 "
                               "--milestone-every-min 0"},
        "why": "the real run on the T4 pair instead",
        "extra": "Roughly a quarter the tokens per session, and fp16 on a "
                 "bf16-native base. Use it if the TPU is unavailable or the "
                 "shakedown failed on it.",
    },
}

SCRIPT = '''"""Generated by launch.py. Edit the repo, not this file."""
import os
import subprocess
import sys

os.environ.update({env!r})

# Kaggle Secrets, never a literal. Absent is fine; it only gates the HF push.
try:
    from kaggle_secrets import UserSecretsClient

    os.environ["HF_TOKEN"] = UserSecretsClient().get_secret("HF_TOKEN")
    print("HF_TOKEN loaded from Kaggle Secrets")
except Exception as exc:
    print(f"no HF_TOKEN ({{type(exc).__name__}}), skipping the Hub push")

subprocess.run(["rm", "-rf", "/kaggle/working/code"], check=False)
subprocess.run(["git", "clone", "--depth", "1", "-q", {repo!r},
                "/kaggle/working/code"], check=True)

code = subprocess.call(["bash", "/kaggle/working/code/kaggle_run.sh",
                        {hours!r}, {base!r}, {tokens!r}])
sys.exit(code)
'''


def have(cmd: str) -> bool:
    return shutil.which(cmd) is not None


def creds_path() -> Path:
    if os.environ.get("KAGGLE_CONFIG_DIR"):
        return Path(os.environ["KAGGLE_CONFIG_DIR"]) / "kaggle.json"
    return Path.home() / ".kaggle" / "kaggle.json"


def preflight(user_override: str = "") -> str:
    """Return the Kaggle username, or exit explaining exactly what is missing.

    Three auth styles are all valid and the CLI accepts any of them, so try in
    the order that asks least of you:
      * kaggle.json, the classic file, which carries the username
      * $KAGGLE_API_TOKEN or ~/.kaggle/access_token, the newer bare token,
        which does not, so the username is read back from the API
      * `kaggle auth login`, OAuth, which caches its own credentials
    """
    if not have("kaggle"):
        raise SystemExit(
            "the kaggle CLI is not installed.\n"
            "  pip install kaggle\n"
            "then rerun this.")
    if user_override:
        return user_override

    path = creds_path()
    if path.exists():
        try:
            return json.loads(path.read_text())["username"]
        except Exception as exc:
            raise SystemExit(f"{path} is not valid Kaggle credentials: {exc}")

    # A bare token authenticates fine but does not say who you are, and the
    # kernel id has to be "username/slug". Read it back off your own kernels.
    if os.environ.get("KAGGLE_API_TOKEN") or (path.parent / "access_token").exists():
        proc = subprocess.run(["kaggle", "kernels", "list", "-m", "--csv"],
                              capture_output=True, text=True)
        for line in proc.stdout.splitlines()[1:]:
            ref = line.split(",")[0].strip()
            if "/" in ref:
                return ref.split("/")[0]
        raise SystemExit(
            "the token authenticates but you have no kernels yet, so the "
            "username cannot be read back from it. Pass --user YOURNAME once.")

    raise SystemExit(
        "no Kaggle credentials found. Any one of these works:\n"
        "  kaggle auth login              OAuth, nothing to store\n"
        "  export KAGGLE_API_TOKEN=...    token from Settings -> API\n"
        f"  {path}                        Create New Token downloads it\n"
        "\nWhile you are in Settings, check Phone Verification is done. Without "
        "it the accelerator dropdown is greyed out and runs silently fall back "
        "to CPU, which trains fine and uselessly slowly.")


def run(cmd: list[str], check: bool = True) -> subprocess.CompletedProcess:
    print("$", " ".join(cmd))
    proc = subprocess.run(cmd, capture_output=True, text=True)
    for stream, out in ((proc.stdout, sys.stdout), (proc.stderr, sys.stderr)):
        if stream:
            print(stream.rstrip(), file=out)
    if check and proc.returncode != 0:
        raise SystemExit(proc.returncode)
    return proc


def write_kernel(work: Path, user: str, slug: str, spec: dict, private: bool) -> None:
    work.mkdir(parents=True, exist_ok=True)
    env = {"DEVICE": spec["device"], "MONITOR": "1", **spec["env"]}
    (work / "run.py").write_text(
        SCRIPT.format(env=env, repo=REPO, hours=spec["hours"],
                      base=spec["base"], tokens=spec["tokens"]),
        encoding="utf-8", newline="\n")
    (work / "kernel-metadata.json").write_text(json.dumps({
        "id": f"{user}/{slug}",
        "title": slug,
        "code_file": "run.py",
        "language": "python",
        "kernel_type": "script",
        "is_private": "true" if private else "false",
        # Needed for the base download, the dataset stream and pip.
        "enable_internet": "true",
        "enable_gpu": "true" if spec["device"] == "gpu" else "false",
        "dataset_sources": [],
        "competition_sources": [],
        "kernel_sources": [],
        "model_sources": [],
    }, indent=1), encoding="utf-8", newline="\n")


def push(work: Path, accelerators: tuple[str, ...]) -> None:
    """Try each accelerator id in turn. Kaggle rotates them without notice."""
    last = None
    for acc in accelerators:
        print(f"\npushing with --accelerator {acc}")
        proc = run(["kaggle", "kernels", "push", "-p", str(work),
                    "--accelerator", acc], check=False)
        if proc.returncode == 0:
            return
        last = proc
        print(f"  {acc} rejected, trying the next id")
    raise SystemExit(
        "every accelerator id was rejected. Two usual causes: the account is "
        "not phone-verified, or Kaggle renamed the ids again. Check "
        "`kaggle kernels push --help` for the current list."
        + (f"\n\nlast error:\n{last.stderr}" if last and last.stderr else ""))


# --------------------------------------------------------------------------- #
# commands
# --------------------------------------------------------------------------- #


def cmd_run(args: argparse.Namespace) -> None:
    spec = RUNS[args.what]
    user = preflight(getattr(args, 'user', ''))
    slug = args.slug or f"llm-reverse-{args.what}"
    work = Path(args.work_dir) / slug

    print(f"about to start:  {args.what}")
    print(f"  base       {spec['base']}")
    print(f"  device     {spec['device']}")
    print(f"  budget     {spec['hours']}h, {spec['tokens']} tokens")
    print(f"  kernel     {user}/{slug}")
    print(f"  why        {spec['why']}")
    if args.what.startswith("shakedown"):
        print("\n  it proves, in order:")
        for i, line in enumerate(PROVES, 1):
            print(f"    {i}. {line}")
        print(f"\n  and specifically: {spec['extra']}")
    else:
        print(f"\n  {spec['extra']}")
    print(f"\nThis consumes roughly {spec['hours']} hours of your weekly "
          f"{spec['device'].upper()} quota.")

    if not args.yes:
        reply = input("\ntype 'go' to push it: ").strip().lower()
        if reply != "go":
            print("not pushed")
            return

    write_kernel(work, user, slug, spec, private=not args.public)
    push(work, TPU_IDS if spec["device"] == "tpu" else GPU_IDS)

    url = f"https://www.kaggle.com/code/{user}/{slug}"
    print(f"\nrunning: {url}")
    print(f"  python launch.py status --slug {slug}")
    print(f"  python launch.py fetch  --slug {slug}")
    print("\nIt runs on Kaggle's servers. Your machine can sleep.")


def cmd_explain(args: argparse.Namespace) -> None:
    print("A shakedown proves, in order:\n")
    for i, line in enumerate(PROVES, 1):
        print(f"  {i}. {line}")
    print("\n2e7 tokens reaches every one of them. Bigger only buys a better "
          "loss curve\non a model you are going to throw away.\n")
    for name, spec in RUNS.items():
        print(f"--- {name}")
        print(f"    base {spec['base']}, {spec['device']}, {spec['hours']}h, "
              f"{spec['tokens']} tokens")
        print(f"    {spec['why']}")
        print(f"    {spec['extra']}\n")


def cmd_status(args: argparse.Namespace) -> None:
    user = preflight(getattr(args, 'user', ''))
    slug = args.slug or "llm-reverse-train"
    run(["kaggle", "kernels", "status", f"{user}/{slug}"], check=False)
    print(f"\nfull log: https://www.kaggle.com/code/{user}/{slug}")


def cmd_fetch(args: argparse.Namespace) -> None:
    user = preflight(getattr(args, 'user', ''))
    slug = args.slug or "llm-reverse-train"
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    run(["kaggle", "kernels", "output", f"{user}/{slug}", "-p", str(out)],
        check=False)
    gguf = sorted(out.rglob("*.gguf"))
    print(f"\ndownloaded to {out}")
    if gguf:
        g = gguf[0]
        print(f"\n  cd {g.parent} && ollama create llm-reverse -f Modelfile")
        print("  ollama run llm-reverse \"\"     # reads right to left")
    else:
        print("no .gguf yet. If the run is still going, wait; if it finished "
              "early, the checkpoints are still in the output and you can "
              "export locally with publish_hf.py.")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)

    for name in RUNS:
        s = sub.add_parser(name, help=RUNS[name]["why"][:60])
        s.add_argument("--slug", default="")
        s.add_argument("--user", default="")
        s.add_argument("--work-dir", default=".launch")
        s.add_argument("--public", action="store_true")
        s.add_argument("--yes", action="store_true", help="skip the confirmation")
        s.set_defaults(func=cmd_run, what=name)

    s = sub.add_parser("explain", help="what each run does, without pushing")
    s.set_defaults(func=cmd_explain)

    s = sub.add_parser("status")
    s.add_argument("--slug", default="")
    s.add_argument("--user", default="")
    s.set_defaults(func=cmd_status)

    s = sub.add_parser("fetch")
    s.add_argument("--slug", default="")
    s.add_argument("--user", default="")
    s.add_argument("--out", default="downloaded")
    s.set_defaults(func=cmd_fetch)

    args = p.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
