"""Generated by launch.py. Edit the repo, not this file."""
import os
import subprocess
import sys

os.environ.update({'DEVICE': 'tpu', 'MONITOR': '1', 'EXPORT': '1'})

# Kaggle Secrets, never a literal. Absent is fine; it only gates the HF push.
try:
    from kaggle_secrets import UserSecretsClient

    os.environ["HF_TOKEN"] = UserSecretsClient().get_secret("HF_TOKEN")
    print("HF_TOKEN loaded from Kaggle Secrets")
except Exception as exc:
    print(f"no HF_TOKEN ({type(exc).__name__}), skipping the Hub push")

subprocess.run(["rm", "-rf", "/kaggle/working/code"], check=False)
subprocess.run(["git", "clone", "--depth", "1", "-q", 'https://github.com/evanwang810/llm-reverse',
                "/kaggle/working/code"], check=True)

code = subprocess.call(["bash", "/kaggle/working/code/kaggle_run.sh",
                        '0.5', 'small-tpu', '2e7'])
sys.exit(code)
